name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:  # at workflow levelenv variables
  MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME}} 
jobs:
  test:
    environment: testing
    env:  # at the job Test level (which will different from PROD)
    # mongodb+srv://eugenio:<password>@cluster0.uvqbwmo.mongodb.net/
      MONGODB_CLUSTER_ADDRESS: cluster0.uvqbwmo.mongodb.net
      MONGODB_USERNAME: eugenio # for later Secrets ${{ secrets.MONGODB_USERNAME}} 
      MONGODB_PASSWORD: MongoKeno2024+ # for later Secrets ${{ secrets.MONGODB_PASSWORD}}  
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }}"
          echo "PORT: ${{ env.PORT }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
          echo "PORT: ${{ env.PORT }}"
